### ISSUE TITLE
인디언 포커 배팅금액 초기화 문제

### ISSUE THREAD

**Issue by sbs1621** [jadru/Casino-J#14]
배팅금액이 초기화가 되지 않습니다.
게임을 2번 실행하게 되면 이전에 사용했던 배팅 금액이 그대로 사용됩니다.

그리고 시작하면 판돈을 처음에 걸게 되는데 그거에 대한 구현도 부족한 것 같습니다

**Comment by jadru** [comment]
ㅋㅋㄹㅃㅃ
