### ISSUE TITLE
#1 : 프로필 스크린에 랭킹 안뜨는거 해결하셈

### ISSUE THREAD

**Issue by jadru** [jadru/Casino-J#4]
해결해!

**Comment by sbs1621** [comment]
### Before
`int userRank;`
### After
`int userRank = -1;`
```
         Vector<String> userOrdered = b.getrank();
         for (int i = 0; i < userOrdered.size(); i++) {
             String now = userOrdered.get(i);
             if (username.equals(now)) {
                 userRank = i;
             }
         }
         userRank++;
```

**Comment by sbs1621** [comment]
Vector<String> userOrdered = b.getrank();
         for (int i = 0; i < userOrdered.size(); i++) {
             String now = userOrdered.get(i);
             if (username.equals(now)) {
                 userRank = i;
             }
         }
         userRank++;
