### ISSUE TITLE
[Issue] 상점에서 카드 구매 후 가격 반영 안됨

### ISSUE THREAD

**Issue by Hoon9901** [jadru/Casino-J#6]
상점에서 카드 구매 하면, 소지한 금액이 차감된 금액으로 안보여지네요.
그런데 메인화면 갔다가 다시 들어오면은 잘 보입니다.

**Comment by sbs1621** [comment]
### 해결했습니당
`userPoint.setText(String.valueOf(b.getPoint(id))); `
