### ISSUE TITLE
[Issue] 4번째 카드 구매 시, 3번째 카드가 구매됨

### ISSUE THREAD

**Issue by Hoon9901** [jadru/Casino-J#7]
상점에서 4번째 카드인 파란색 카드를 구매하면, 보라색 카드가 사집니다.

**Comment by sbs1621** [comment]
해당 이슈는 SQLiteManager에 오타로 인해 발생해서 해결했습니다~

**Comment by sbs1621** [comment]
### Before
`stmt.execute("update player set skin3 = 1" + " where id = '" + id + "'");`
### After
`stmt.execute("update player set skin4 = 1" + " where id = '" + id + "'");`
